// Generated from contract/sdk-operations.json by scripts/sync-operations.mjs.
// The transport and public service API remain hand-written.

export interface OperationDefinition {
  readonly method: "delete" | "get" | "patch" | "post" | "put";
  readonly path: string;
  readonly tag: string;
  readonly authenticated: boolean;
  readonly scopes: readonly string[];
  readonly requestContentTypes: readonly string[];
  readonly responseStatuses: readonly string[];
  readonly capabilities: readonly string[];
}

export const OPERATIONS = {
  "cancelAccountConnection": {
    method: "delete",
    path: "/connection-sessions/{id}",
    tag: "Connections",
    authenticated: true,
    scopes: ["accounts:write"],
    requestContentTypes: [],
    responseStatuses: ["204","401","403","404","409","500"],
    capabilities: ["authenticated"],
  },
  "changePassword": {
    method: "put",
    path: "/me/password",
    tag: "Profile",
    authenticated: true,
    scopes: ["profile:write"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["204","400","401","403","413","415","422","500"],
    capabilities: ["authenticated"],
  },
  "checkPostConstraints": {
    method: "post",
    path: "/posts/constraints",
    tag: "Posts",
    authenticated: true,
    scopes: ["posts:read"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["200","400","401","403","413","415","422","500"],
    capabilities: ["authenticated"],
  },
  "confirmAccountConnection": {
    method: "post",
    path: "/connection-sessions/{id}/confirm",
    tag: "Connections",
    authenticated: true,
    scopes: ["accounts:write"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["200","400","401","403","404","409","413","415","422","500"],
    capabilities: ["authenticated","idempotency_key"],
  },
  "createContentTemplate": {
    method: "post",
    path: "/me/templates",
    tag: "Preferences",
    authenticated: true,
    scopes: ["profile:write"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["201","400","401","403","409","413","415","422","500"],
    capabilities: ["authenticated"],
  },
  "createGroup": {
    method: "post",
    path: "/groups",
    tag: "Groups",
    authenticated: true,
    scopes: ["groups:write"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["201","400","401","403","413","415","422","500"],
    capabilities: ["authenticated"],
  },
  "createPersonalToken": {
    method: "post",
    path: "/personal-tokens",
    tag: "Personal tokens",
    authenticated: true,
    scopes: ["profile:write"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["201","400","401","403","409","413","415","422","500"],
    capabilities: ["authenticated"],
  },
  "createPostDraft": {
    method: "post",
    path: "/posts",
    tag: "Posts",
    authenticated: true,
    scopes: ["posts:write"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["201","400","401","403","409","413","415","422","500"],
    capabilities: ["authenticated","idempotency_key"],
  },
  "createWebhook": {
    method: "post",
    path: "/webhooks",
    tag: "Webhooks",
    authenticated: true,
    scopes: ["webhooks:write"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["201","400","401","403","409","413","415","422","500"],
    capabilities: ["authenticated","idempotency_key"],
  },
  "deleteContentTemplate": {
    method: "delete",
    path: "/me/templates/{id}",
    tag: "Preferences",
    authenticated: true,
    scopes: ["profile:write"],
    requestContentTypes: [],
    responseStatuses: ["204","401","403","404","412","428","500"],
    capabilities: ["authenticated","optimistic_concurrency"],
  },
  "deleteGroup": {
    method: "delete",
    path: "/groups/{id}",
    tag: "Groups",
    authenticated: true,
    scopes: ["groups:write"],
    requestContentTypes: [],
    responseStatuses: ["204","401","403","404","412","428","500"],
    capabilities: ["authenticated","optimistic_concurrency"],
  },
  "deleteMe": {
    method: "delete",
    path: "/me",
    tag: "Profile",
    authenticated: true,
    scopes: ["profile:write"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["202","400","401","403","409","413","415","422","500"],
    capabilities: ["async_job","authenticated","idempotency_key"],
  },
  "deleteMedia": {
    method: "delete",
    path: "/media/{id}",
    tag: "Media",
    authenticated: true,
    scopes: ["media:write"],
    requestContentTypes: [],
    responseStatuses: ["204","401","403","404","409","500"],
    capabilities: ["authenticated"],
  },
  "deletePostDraft": {
    method: "delete",
    path: "/posts/{id}",
    tag: "Posts",
    authenticated: true,
    scopes: ["posts:write"],
    requestContentTypes: [],
    responseStatuses: ["204","401","403","404","409","412","428","500"],
    capabilities: ["authenticated","optimistic_concurrency"],
  },
  "deletePostEverywhere": {
    method: "post",
    path: "/posts/{id}/delete-everywhere",
    tag: "Publication jobs",
    authenticated: true,
    scopes: ["posts:publish"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["202","400","401","403","404","409","413","415","422","500"],
    capabilities: ["async_job","authenticated","idempotency_key"],
  },
  "deleteWebhook": {
    method: "delete",
    path: "/webhooks/{webhook_id}",
    tag: "Webhooks",
    authenticated: true,
    scopes: ["webhooks:write"],
    requestContentTypes: [],
    responseStatuses: ["204","401","403","404","412","428","500"],
    capabilities: ["authenticated","optimistic_concurrency"],
  },
  "disconnectAccount": {
    method: "delete",
    path: "/accounts/{id}",
    tag: "Accounts",
    authenticated: true,
    scopes: ["accounts:write"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","404","409","500"],
    capabilities: ["authenticated"],
  },
  "forgotPassword": {
    method: "post",
    path: "/auth/forgot-password",
    tag: "Auth",
    authenticated: false,
    scopes: [],
    requestContentTypes: ["application/json"],
    responseStatuses: ["202","400","413","415","422","429","500","503"],
    capabilities: ["async_job"],
  },
  "getAccount": {
    method: "get",
    path: "/accounts/{id}",
    tag: "Accounts",
    authenticated: true,
    scopes: ["accounts:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","404","500"],
    capabilities: ["authenticated"],
  },
  "getAccountConnection": {
    method: "get",
    path: "/connection-sessions/{id}",
    tag: "Connections",
    authenticated: true,
    scopes: ["accounts:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","404","500"],
    capabilities: ["authenticated"],
  },
  "getAnalyticsAudience": {
    method: "get",
    path: "/analytics/audience",
    tag: "Analytics",
    authenticated: true,
    scopes: ["analytics:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","422","500"],
    capabilities: ["authenticated"],
  },
  "getAnalyticsNetworks": {
    method: "get",
    path: "/analytics/networks",
    tag: "Analytics",
    authenticated: true,
    scopes: ["analytics:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","422","500"],
    capabilities: ["authenticated"],
  },
  "getAnalyticsSummary": {
    method: "get",
    path: "/analytics/summary",
    tag: "Analytics",
    authenticated: true,
    scopes: ["analytics:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","422","500"],
    capabilities: ["authenticated"],
  },
  "getAnalyticsTimeseries": {
    method: "get",
    path: "/analytics/timeseries",
    tag: "Analytics",
    authenticated: true,
    scopes: ["analytics:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","422","500"],
    capabilities: ["authenticated"],
  },
  "getContentTemplate": {
    method: "get",
    path: "/me/templates/{id}",
    tag: "Preferences",
    authenticated: true,
    scopes: ["profile:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","404","500"],
    capabilities: ["authenticated"],
  },
  "getGroup": {
    method: "get",
    path: "/groups/{id}",
    tag: "Groups",
    authenticated: true,
    scopes: ["groups:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","404","500"],
    capabilities: ["authenticated"],
  },
  "getMe": {
    method: "get",
    path: "/me",
    tag: "Profile",
    authenticated: true,
    scopes: ["profile:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","500"],
    capabilities: ["authenticated"],
  },
  "getMedia": {
    method: "get",
    path: "/media/{id}",
    tag: "Media",
    authenticated: true,
    scopes: ["media:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","404","500"],
    capabilities: ["authenticated"],
  },
  "getMediaContent": {
    method: "get",
    path: "/media/{id}/content",
    tag: "Media",
    authenticated: true,
    scopes: ["media:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","404","500"],
    capabilities: ["authenticated","binary_response"],
  },
  "getNetwork": {
    method: "get",
    path: "/networks/{key}",
    tag: "Networks",
    authenticated: true,
    scopes: ["networks:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","404","422","500"],
    capabilities: ["authenticated"],
  },
  "getOpenApi": {
    method: "get",
    path: "/openapi.json",
    tag: "System",
    authenticated: false,
    scopes: [],
    requestContentTypes: [],
    responseStatuses: ["200","500"],
    capabilities: [],
  },
  "getPersonalToken": {
    method: "get",
    path: "/personal-tokens/{id}",
    tag: "Personal tokens",
    authenticated: true,
    scopes: ["profile:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","404","500"],
    capabilities: ["authenticated"],
  },
  "getPost": {
    method: "get",
    path: "/posts/{id}",
    tag: "Posts",
    authenticated: true,
    scopes: ["posts:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","404","500"],
    capabilities: ["authenticated"],
  },
  "getPublicationJob": {
    method: "get",
    path: "/jobs/{job_id}",
    tag: "Publication jobs",
    authenticated: true,
    scopes: ["jobs:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","404","500"],
    capabilities: ["authenticated"],
  },
  "getSession": {
    method: "get",
    path: "/sessions/{id}",
    tag: "Sessions",
    authenticated: true,
    scopes: ["profile:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","404","500"],
    capabilities: ["authenticated"],
  },
  "getSignatures": {
    method: "get",
    path: "/me/signatures",
    tag: "Preferences",
    authenticated: true,
    scopes: ["profile:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","500"],
    capabilities: ["authenticated"],
  },
  "getSignedMediaContent": {
    method: "get",
    path: "/media-content",
    tag: "Media",
    authenticated: false,
    scopes: [],
    requestContentTypes: [],
    responseStatuses: ["200","404","422","500"],
    capabilities: ["binary_response"],
  },
  "getWebhook": {
    method: "get",
    path: "/webhooks/{webhook_id}",
    tag: "Webhooks",
    authenticated: true,
    scopes: ["webhooks:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","404","500"],
    capabilities: ["authenticated"],
  },
  "getWebhookDelivery": {
    method: "get",
    path: "/webhooks/{webhook_id}/deliveries/{delivery_id}",
    tag: "Webhooks",
    authenticated: true,
    scopes: ["webhooks:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","404","500"],
    capabilities: ["authenticated"],
  },
  "listAccounts": {
    method: "get",
    path: "/accounts",
    tag: "Accounts",
    authenticated: true,
    scopes: ["accounts:read"],
    requestContentTypes: [],
    responseStatuses: ["200","400","401","403","422","500"],
    capabilities: ["authenticated","cursor_pagination"],
  },
  "listAnalyticsPosts": {
    method: "get",
    path: "/analytics/posts",
    tag: "Analytics",
    authenticated: true,
    scopes: ["analytics:read"],
    requestContentTypes: [],
    responseStatuses: ["200","400","401","403","422","500"],
    capabilities: ["authenticated","cursor_pagination"],
  },
  "listAuditEvents": {
    method: "get",
    path: "/audit-events",
    tag: "Audit",
    authenticated: true,
    scopes: ["profile:read"],
    requestContentTypes: [],
    responseStatuses: ["200","400","401","403","422","500"],
    capabilities: ["authenticated","cursor_pagination"],
  },
  "listCalendarEvents": {
    method: "get",
    path: "/calendar",
    tag: "Calendar",
    authenticated: true,
    scopes: ["calendar:read"],
    requestContentTypes: [],
    responseStatuses: ["200","400","401","403","422","500"],
    capabilities: ["authenticated","cursor_pagination"],
  },
  "listContentTemplates": {
    method: "get",
    path: "/me/templates",
    tag: "Preferences",
    authenticated: true,
    scopes: ["profile:read"],
    requestContentTypes: [],
    responseStatuses: ["200","400","401","403","422","500"],
    capabilities: ["authenticated","cursor_pagination"],
  },
  "listGroups": {
    method: "get",
    path: "/groups",
    tag: "Groups",
    authenticated: true,
    scopes: ["groups:read"],
    requestContentTypes: [],
    responseStatuses: ["200","400","401","403","422","500"],
    capabilities: ["authenticated","cursor_pagination"],
  },
  "listMedia": {
    method: "get",
    path: "/media",
    tag: "Media",
    authenticated: true,
    scopes: ["media:read"],
    requestContentTypes: [],
    responseStatuses: ["200","400","401","403","422","500"],
    capabilities: ["authenticated","cursor_pagination"],
  },
  "listNetworks": {
    method: "get",
    path: "/networks",
    tag: "Networks",
    authenticated: true,
    scopes: ["networks:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","422","500"],
    capabilities: ["authenticated"],
  },
  "listPersonalTokens": {
    method: "get",
    path: "/personal-tokens",
    tag: "Personal tokens",
    authenticated: true,
    scopes: ["profile:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","500"],
    capabilities: ["authenticated"],
  },
  "listPosts": {
    method: "get",
    path: "/posts",
    tag: "Posts",
    authenticated: true,
    scopes: ["posts:read"],
    requestContentTypes: [],
    responseStatuses: ["200","400","401","403","422","500"],
    capabilities: ["authenticated","cursor_pagination"],
  },
  "listPublicationJobs": {
    method: "get",
    path: "/jobs",
    tag: "Publication jobs",
    authenticated: true,
    scopes: ["jobs:read"],
    requestContentTypes: [],
    responseStatuses: ["200","400","401","403","422","500"],
    capabilities: ["authenticated","cursor_pagination"],
  },
  "listSessions": {
    method: "get",
    path: "/sessions",
    tag: "Sessions",
    authenticated: true,
    scopes: ["profile:read"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","500"],
    capabilities: ["authenticated"],
  },
  "listWebhookDeliveries": {
    method: "get",
    path: "/webhooks/{webhook_id}/deliveries",
    tag: "Webhooks",
    authenticated: true,
    scopes: ["webhooks:read"],
    requestContentTypes: [],
    responseStatuses: ["200","400","401","403","404","422","500"],
    capabilities: ["authenticated","cursor_pagination"],
  },
  "listWebhooks": {
    method: "get",
    path: "/webhooks",
    tag: "Webhooks",
    authenticated: true,
    scopes: ["webhooks:read"],
    requestContentTypes: [],
    responseStatuses: ["200","400","401","403","422","500"],
    capabilities: ["authenticated","cursor_pagination"],
  },
  "login": {
    method: "post",
    path: "/auth/login",
    tag: "Auth",
    authenticated: false,
    scopes: [],
    requestContentTypes: ["application/json"],
    responseStatuses: ["200","400","401","413","415","422","429","500","503"],
    capabilities: [],
  },
  "logout": {
    method: "post",
    path: "/auth/logout",
    tag: "Auth",
    authenticated: true,
    scopes: ["profile:read"],
    requestContentTypes: [],
    responseStatuses: ["204","401","403","500"],
    capabilities: ["authenticated"],
  },
  "logoutAll": {
    method: "post",
    path: "/auth/logout-all",
    tag: "Auth",
    authenticated: true,
    scopes: ["profile:read"],
    requestContentTypes: [],
    responseStatuses: ["204","401","403","500"],
    capabilities: ["authenticated"],
  },
  "ping": {
    method: "get",
    path: "/ping",
    tag: "System",
    authenticated: false,
    scopes: [],
    requestContentTypes: [],
    responseStatuses: ["200","500"],
    capabilities: [],
  },
  "publishPost": {
    method: "post",
    path: "/posts/{id}/publish",
    tag: "Publication jobs",
    authenticated: true,
    scopes: ["posts:publish"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["202","400","401","403","404","409","412","413","415","422","500"],
    capabilities: ["async_job","authenticated","idempotency_key"],
  },
  "refresh": {
    method: "post",
    path: "/auth/refresh",
    tag: "Auth",
    authenticated: false,
    scopes: [],
    requestContentTypes: ["application/json"],
    responseStatuses: ["200","400","401","413","415","422","429","500","503"],
    capabilities: [],
  },
  "register": {
    method: "post",
    path: "/auth/register",
    tag: "Auth",
    authenticated: false,
    scopes: [],
    requestContentTypes: ["application/json"],
    responseStatuses: ["202","400","413","415","422","429","500","503"],
    capabilities: ["async_job"],
  },
  "replaceGroupAccounts": {
    method: "put",
    path: "/groups/{id}/accounts",
    tag: "Groups",
    authenticated: true,
    scopes: ["groups:write"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["200","400","401","403","404","412","413","415","422","428","500"],
    capabilities: ["authenticated","optimistic_concurrency"],
  },
  "replaceSignatures": {
    method: "put",
    path: "/me/signatures",
    tag: "Preferences",
    authenticated: true,
    scopes: ["profile:write"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["200","400","401","403","413","415","422","500"],
    capabilities: ["authenticated"],
  },
  "resendVerification": {
    method: "post",
    path: "/auth/email/resend",
    tag: "Auth",
    authenticated: false,
    scopes: [],
    requestContentTypes: ["application/json"],
    responseStatuses: ["202","400","413","415","422","429","500","503"],
    capabilities: ["async_job"],
  },
  "resetPassword": {
    method: "post",
    path: "/auth/reset-password",
    tag: "Auth",
    authenticated: false,
    scopes: [],
    requestContentTypes: ["application/json"],
    responseStatuses: ["204","400","413","415","422","429","500","503"],
    capabilities: [],
  },
  "retryPostTargets": {
    method: "post",
    path: "/posts/{id}/retry",
    tag: "Publication jobs",
    authenticated: true,
    scopes: ["posts:publish"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["202","400","401","403","404","409","413","415","422","500"],
    capabilities: ["async_job","authenticated","idempotency_key"],
  },
  "retryWebhookDelivery": {
    method: "post",
    path: "/webhooks/{webhook_id}/deliveries/{delivery_id}/retry",
    tag: "Webhooks",
    authenticated: true,
    scopes: ["webhooks:write"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["202","400","401","403","404","409","413","415","422","500"],
    capabilities: ["async_job","authenticated","idempotency_key"],
  },
  "revokePersonalToken": {
    method: "delete",
    path: "/personal-tokens/{id}",
    tag: "Personal tokens",
    authenticated: true,
    scopes: ["profile:write"],
    requestContentTypes: [],
    responseStatuses: ["204","401","403","404","500"],
    capabilities: ["authenticated"],
  },
  "revokeSession": {
    method: "delete",
    path: "/sessions/{id}",
    tag: "Sessions",
    authenticated: true,
    scopes: ["profile:write"],
    requestContentTypes: [],
    responseStatuses: ["204","401","403","404","500"],
    capabilities: ["authenticated"],
  },
  "rotatePersonalToken": {
    method: "post",
    path: "/personal-tokens/{id}/rotate",
    tag: "Personal tokens",
    authenticated: true,
    scopes: ["profile:write"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","404","409","500"],
    capabilities: ["authenticated"],
  },
  "rotateWebhookSecret": {
    method: "post",
    path: "/webhooks/{webhook_id}/rotate-secret",
    tag: "Webhooks",
    authenticated: true,
    scopes: ["webhooks:write"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["200","400","401","403","404","409","413","415","422","500"],
    capabilities: ["authenticated","idempotency_key"],
  },
  "schedulePost": {
    method: "post",
    path: "/posts/{id}/schedule",
    tag: "Posts",
    authenticated: true,
    scopes: ["posts:publish"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["200","400","401","403","404","409","412","413","415","422","428","500"],
    capabilities: ["authenticated","optimistic_concurrency"],
  },
  "startAccountConnection": {
    method: "post",
    path: "/connection-sessions",
    tag: "Connections",
    authenticated: true,
    scopes: ["accounts:write"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["200","201","400","401","403","409","413","415","422","500","502"],
    capabilities: ["authenticated","idempotency_key"],
  },
  "testWebhook": {
    method: "post",
    path: "/webhooks/{webhook_id}/test",
    tag: "Webhooks",
    authenticated: true,
    scopes: ["webhooks:write"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["202","400","401","403","404","409","413","415","422","500"],
    capabilities: ["async_job","authenticated","idempotency_key"],
  },
  "unschedulePost": {
    method: "post",
    path: "/posts/{id}/unschedule",
    tag: "Posts",
    authenticated: true,
    scopes: ["posts:publish"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","404","409","412","428","500"],
    capabilities: ["authenticated","optimistic_concurrency"],
  },
  "updateContentTemplate": {
    method: "patch",
    path: "/me/templates/{id}",
    tag: "Preferences",
    authenticated: true,
    scopes: ["profile:write"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["200","400","401","403","404","412","413","415","422","428","500"],
    capabilities: ["authenticated","optimistic_concurrency"],
  },
  "updateGroup": {
    method: "patch",
    path: "/groups/{id}",
    tag: "Groups",
    authenticated: true,
    scopes: ["groups:write"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["200","400","401","403","404","412","413","415","422","428","500"],
    capabilities: ["authenticated","optimistic_concurrency"],
  },
  "updateMe": {
    method: "patch",
    path: "/me",
    tag: "Profile",
    authenticated: true,
    scopes: ["profile:write"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["200","400","401","403","413","415","422","500"],
    capabilities: ["authenticated"],
  },
  "updatePersonalToken": {
    method: "patch",
    path: "/personal-tokens/{id}",
    tag: "Personal tokens",
    authenticated: true,
    scopes: ["profile:write"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["200","400","401","403","404","409","413","415","422","500"],
    capabilities: ["authenticated"],
  },
  "updatePostDraft": {
    method: "patch",
    path: "/posts/{id}",
    tag: "Posts",
    authenticated: true,
    scopes: ["posts:write"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["200","400","401","403","404","409","412","413","415","422","428","500"],
    capabilities: ["authenticated","optimistic_concurrency"],
  },
  "updateWebhook": {
    method: "patch",
    path: "/webhooks/{webhook_id}",
    tag: "Webhooks",
    authenticated: true,
    scopes: ["webhooks:write"],
    requestContentTypes: ["application/json"],
    responseStatuses: ["200","400","401","403","404","409","412","413","415","422","428","500"],
    capabilities: ["authenticated","optimistic_concurrency"],
  },
  "uploadMedia": {
    method: "post",
    path: "/media",
    tag: "Media",
    authenticated: true,
    scopes: ["media:write"],
    requestContentTypes: ["multipart/form-data"],
    responseStatuses: ["201","401","403","409","413","415","422","429","500","503"],
    capabilities: ["authenticated","multipart_upload"],
  },
  "verifyAccount": {
    method: "post",
    path: "/accounts/{id}/verify",
    tag: "Accounts",
    authenticated: true,
    scopes: ["accounts:write"],
    requestContentTypes: [],
    responseStatuses: ["200","401","403","404","422","500","502"],
    capabilities: ["authenticated"],
  },
  "verifyEmail": {
    method: "post",
    path: "/auth/email/verify",
    tag: "Auth",
    authenticated: false,
    scopes: [],
    requestContentTypes: ["application/json"],
    responseStatuses: ["204","400","413","415","422","429","500","503"],
    capabilities: [],
  },
} as const satisfies Readonly<Record<string, OperationDefinition>>;

